### ISSUE TITLE
Support composer-installer-v4

### ISSUE THREAD

**Issue by a-r-m-i-n** [a-r-m-i-n/min#12]
According to https://github.com/a-r-m-i-n/min/issues/11#issuecomment-1211736815 the relative file paths in CSS files are not resolved correctly, when the new [composer-installer v4](https://github.com/TYPO3/CmsComposerInstallers/releases/tag/v4.0.0-RC1) is involved.

**Comment by a-r-m-i-n** [comment]
From the README of composer-installer-v4:

> The public resource URL can not be derived any more from the absolute path to the file by stripping off some path part, but only by
> passing the absolute path to \TYPO3\CMS\Core\Utility\PathUtility::getAbsoluteWebPath
> Example:
use TYPO3\CMS\Core\Utility\PathUtility;
use TYPO3\CMS\Core\Utility\GeneralUtility;
>
> PathUtility::getAbsoluteWebPath(GeneralUtility::getFileAbsFileName('EXT:ext_key/Resources/Public/Icons/Extension.svg'));

Currerently I'm using substr to make the absolute server path relative. That's probably the issue.

**Comment by a-r-m-i-n** [comment]
The problem with the new assets of composer-installer v4 is, that somehow you need to resolve the hash of the asset/symlink pointing to `EXT:my_ext/Resources/Public/`.

In SCSS, to address font files, I need to prepend this to every font file:
```
$fontPath: '../../../_assets/1031f6efa8587629b685351ed90c99bf/Fonts';
```

**Some questions I have:**

- Does this hash change or is it basically an md5 hash of the path pointing to?
- Is there an API existing, to resolve the path to the asset?

**Comment by Patta** [comment]
@a-r-m-i-n 

> Does this hash change or is it basically an md5 hash of the path pointing to?

Yes, i think so. The path is always the same id in my tests.

> Is there an API existing, to resolve the path to the asset?

TYPO3's internal resource resolver. EXT: ....
