### ISSUE TITLE
TYPO3 12

### ISSUE THREAD

**Issue by fritzdacat** [a-r-m-i-n/min#18]
Hello, are there any plans for TYPO3 12 support?

**Comment by devtroll** [comment]
Any information about a update ?

**Comment by a-r-m-i-n** [comment]
Not yet. Probably around the Dev Days in August.

**Comment by fritzdacat** [comment]
I'm at the TYPO3 Dev Days too. Maybe I can help you somehow..

**Comment by abvdveen** [comment]
👍

**Comment by a-r-m-i-n** [comment]
Version 3.0 is out now! 🎉
