### ISSUE TITLE
Compression of AssetCollector Assets

### ISSUE THREAD

**Issue by Patta** [a-r-m-i-n/min#2]
Thanks armin for version 2 of this must have extension! 
In the commit logs i saw a roadmap v2.1 task to provide optional CSS/JS compression for the "new" asset viewhelper. Is that still on your roadmap? That would be really cool, because the core still does not provide such a feature. https://forge.typo3.org/issues/91312

**Comment by a-r-m-i-n** [comment]
Hi Patta,
as mentioned in the brand new documentation, this is on the schedule: https://github.com/a-r-m-i-n/min/blob/master/Documentation/Welcome.rst#roadmap--missing-features

**Comment by Patta** [comment]
Ah, sorry for spamming, my fault.

**Comment by a-r-m-i-n** [comment]
This feature is implemented, now. And it will get released in version 2.1.0
