### ISSUE TITLE
New Tag for TS fix

### ISSUE THREAD

**Issue by tgriessbach** [a-r-m-i-n/min#27]
Hello,
could you create a new tag so that we get this fix: https://github.com/a-r-m-i-n/min/commit/4966c4cd8e6aa7edab9b77902cdb3d9cc9c937b7
and prevent deprecation warnings?

Thank you very much!

**Comment by a-r-m-i-n** [comment]
Yes yes...

**Comment by tgriessbach** [comment]
I'm sorry, maybe I'm missing something.
Have you pushed a new tag yet?

The last one showing for me here: https://github.com/a-r-m-i-n/min/tags
is still 3.0.1

**Comment by a-r-m-i-n** [comment]
Nope, not yet. First I'm going to fix the remaining bugs. Please stay tuned.
