### ISSUE TITLE
Possible error in ext_localconf.php?

### ISSUE THREAD

**Issue by maslme** [a-r-m-i-n/min#9]
I got several Log Entries:
"Core: Exception handler (CLI): Uncaught TYPO3 Exception: syntax error, unexpected '=' | ParseError thrown in file .../typo3temp/var/cache/code/core/ext_localconf_ccd1fa08068a0a0f1060a754943cb44d743d8f59.php in line 2028"

I could figured out, that the error point to line 18 in the EXT:min/ext_localconf.php.

I use php 7.4.28

**Comment by a-r-m-i-n** [comment]
Hi Maslme, indeed there is an issue with lower PHP versions. The `??=` syntax is not existing in 7.4.
